### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by ukBaz** [jackmitch/libsoc#53]
From a [discussion ](http://www.96boards.org/forums/topic/upcoming-debian-april-release-for-db410c-call-for-testing/#post-14002)on the 96boards forum it would appear that the version of libsoc available is quite old and without the Python binding.

Is there a newer release planned?

**Comment by jackmitch** [comment]
There certainly is, https://plus.google.com/+JackMitchell/posts/WxgZi4S7FNS

**Comment by jackmitch** [comment]
Hi Barry,

The new release has now been cut.

Cheers!
