### ISSUE TITLE
Syntax error when running "./configure"

### ISSUE THREAD

**Issue by nkolban** [jackmitch/libsoc#61]
I am trying to build libsoc on the CHIP environment.  When I run "./configure", execution ends with the following:

```
...
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for library containing pthread_create, pthread_cancel... -lpthread
./configure: line 11761: syntax error near unexpected token `PYTHON,'
./configure: line 11761: `	PKG_CHECK_MODULES(PYTHON, python-"$PYTHON_VERSION")'
```

**Comment by nkolban** [comment]
I had failed to install pkg-tools

**Comment by hossboss** [comment]
The comments on this issue got me closer, but not all the way. The package missing was, on CHIP with OS v4.4, `pkg-config`. I also had to provide the python path to `configure` to get the build to work correctly--`configure` would succeed but then `make` would bomb, with `#include <Python.h>` not resolving. For good measure I also installed python-dev.

```
sudo apt-get install pkg-config python-dev
autoreconf -i
./configure --enable-python=/usr/bin/python2.7
make
```

**Comment by jackmitch** [comment]
Hi,

This information is present in the documentation, did you miss it or were you following instructions from elsewhere?

http://jackmitch.github.io/libsoc/#manually-building

Cheers,
Jack.

**Comment by kamomil** [comment]
Hi, I'm having the same issue, 
running on a dragonboard410c :

`./configure --enable-python=/usr/bin/python2.7 --enable-board=dragonboard410c`

I get:


> ./configure: line 12269: syntax error near unexpected token `PYTHON,'                                                              

> ./configure: line 12269: `      PKG_CHECK_MODULES(PYTHON, python-"$PYTHON_VERSION")'  

Not sure how to fix that
Thanks

**Comment by jackmitch** [comment]
Have you got pkg-tools installed on your host?

**Comment by kamomil** [comment]
no, it is installed using `pip3 install deb-pkg-tools`  ?

**Comment by yegorich** [comment]
@kamomil you need [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/).
