### ISSUE TITLE
libsoc_gpio.h depends on stdlib.h

### ISSUE THREAD

**Issue by nkolban** [jackmitch/libsoc#62]
The header file called libsoc_gpio.h references constants called `EXIT_FAILURE` and `EXIT_SUCCESS`.  These are defined in `stdlib.h` however `stdlib.h` isn't included in `libsoc_gpio.h` resulting in a compilation failure if the programmer does not include `stdlib.h` before including `libsoc_gpio.h`.  This issue requests one of the following:

1) Explicitly include `stdlib.h` in `libsoc_gpio.h`
or
2) Remove the dependency on `stdlib.h` from `libsoc_gpio.h`.

**Comment by jackmitch** [comment]
Fixed, thanks!
