### ISSUE TITLE
Change in spi.c

### ISSUE THREAD

**Issue by LiveWang** [jackmitch/libsoc#63]
I think line 226 in spi.c: 
`return EXIT_FAILURE;`
should be changed to: 
`return MODE_ERROR;` or `exit(EXIT_FAILURE);`

Because the function spi_mode libsoc_spi_get_mode(spi *spi) returns a spi_mode which can be 0, 1, 2, 3, 4, MODE_1 is 1 and MODE_ERROR is 4. In some extent, return EXIT_FAILURE is equal to return 1.  So this may cause confusion when I get the return value of the function.

**Comment by jackmitch** [comment]
Good spot, thanks! Fixed by changing to MODE_ERROR.
