### ISSUE TITLE
multiple definitions of enum *mode* in gpio and pwm libs

### ISSUE THREAD

**Issue by bhuvanchandra** [jackmitch/libsoc#77]
When using GPIO and PWM libs together, compiling fails with multiple definitions as same variables are defined in both libsoc_gpio.h and libsoc_pwm.h. [Rename the variables to avoid redefinition](https://github.com/bhuvanchandra/libsoc/commit/26889b132447d15eb0deef953bd1813bf40861bd).

**Comment by jackmitch** [comment]
Being address in #78

**Comment by jackmitch** [comment]
Merged.
