### ISSUE TITLE
SPI - 16-bit Mode

### ISSUE THREAD

**Issue by compiaffe** [jackmitch/libsoc#9]
Hi Jack, great library.

I am trying to access an Analog Devices ADIS16480 via SPI on a beaglebone black using your library. It needs SPI mode 3, SPI freq.<16MHz and the 16-bit mode. Its on SPI1 and the HDMI virtual cape is disabled.

So I tried using your  libsoc_spi_set_bits_per_word function but realised that I cannot place a 16 bit word into the tx buffer... When splitting the 16 bit word into two 8 bit words and placing them into the buffer I realised (Oscilloscope) that the 8 bit words get padded with 8 zeros as the MSBs:
0x80 = 0b 1000 0000 --- becomes---> 0x0080 = 0b 0000 0000 1000 0000

What is necessary to be able to place 16 bits into the tx buffer? Does the underlying ioctl() support this?

Thanks alot,

Rapha

P.S: It does seem to work by setting it to 8-bit mode and just using two tx slots per command... But it is confusing given the 16 bit option.

**Comment by feromero12** [comment]
good morning
I'm working with beaglebone black, wanting to do SPI communication with a current sensor, I've already built the devices tree, and I've been able to make it work in python, with adafruit, or in c with the .h libraries, but I've only been able to get the Beaglebone black trasnmit, receive 8-bit data, I need to implement a 16-bit tx / rx, look in the forum that modifying a library can do that, it is possible to access that library and be able to use in my 16-bit transmission .
Thank you for your attention

**Comment by feromero12** [comment]
good morning
I'm working with beaglebone black, wanting to do SPI communication with a current sensor, I've already built the devices tree, and I've been able to make it work in python, with adafruit, or in c with the .h libraries, but I've only been able to get the Beaglebone black trasnmit, receive 8-bit data, I need to implement a 16-bit tx / rx, look in the forum that modifying a library can do that, it is possible to access that library and be able to use in my 16-bit transmission .
Thank you for your attention

**Comment by jackmitch** [comment]
I had thought this was fixed, I'll try and take another look at it soon.

**Comment by jackmitch** [comment]
Actually, it looks as if this is still fixed, re-read how the spi_rw works and try the above solution. If it still doesn't work post some code and I'll see if there is anything odd going on.
