### ISSUE TITLE
pwm device on new kernel

### ISSUE THREAD

**Issue by gkarsai** [jackmitch/libsoc#97]
According to https://stackoverflow.com/questions/50204329/pwm-chip-to-pin-mapping-on-beaglebone-black-v4-14/ the name of the exported device is pwm-0:0 (for chip 0/output 0) not pwm0. This change breaks the code in lib/pwm.c

**Comment by jackmitch** [comment]
Hi, I believe this is due to something that TI do in their vendor kernel and as such is not present in mainline Linux. I'm afraid I can't change this as it would break mainline kernel support, the correct solution would be to ask TI to conform to the upstream kernel standard.
